//
//  LanguageCatalog.swift
//  WhisperLive-iOS-Client
//
//  Provides the list of languages supported by Seamless M4T export for UI selection.
//

import Foundation

struct LanguageOption: Identifiable, Hashable {
    let code: String
    let name: String

    var id: String { code }
}

enum LanguageCatalog {
    /// Seamless M4T text translation targets.
    static let all: [LanguageOption] = [
        LanguageOption(code: "af", name: "Afrikaans"),
        LanguageOption(code: "am", name: "Amharic"),
        LanguageOption(code: "ar", name: "Arabic"),
        LanguageOption(code: "as", name: "Assamese"),
        LanguageOption(code: "az", name: "Azerbaijani"),
        LanguageOption(code: "be", name: "Belarusian"),
        LanguageOption(code: "bg", name: "Bulgarian"),
        LanguageOption(code: "bn", name: "Bengali"),
        LanguageOption(code: "bs", name: "Bosnian"),
        LanguageOption(code: "ca", name: "Catalan"),
        LanguageOption(code: "ceb", name: "Cebuano"),
        LanguageOption(code: "ckb", name: "Central Kurdish"),
        LanguageOption(code: "co", name: "Corsican"),
        LanguageOption(code: "cs", name: "Czech"),
        LanguageOption(code: "cy", name: "Welsh"),
        LanguageOption(code: "da", name: "Danish"),
        LanguageOption(code: "de", name: "German"),
        LanguageOption(code: "doi", name: "Dogri"),
        LanguageOption(code: "dv", name: "Dhivehi"),
        LanguageOption(code: "el", name: "Greek"),
        LanguageOption(code: "en", name: "English"),
        LanguageOption(code: "eo", name: "Esperanto"),
        LanguageOption(code: "es", name: "Spanish"),
        LanguageOption(code: "et", name: "Estonian"),
        LanguageOption(code: "eu", name: "Basque"),
        LanguageOption(code: "fa", name: "Persian"),
        LanguageOption(code: "fi", name: "Finnish"),
        LanguageOption(code: "fil", name: "Filipino"),
        LanguageOption(code: "fj", name: "Fijian"),
        LanguageOption(code: "fr", name: "French"),
        LanguageOption(code: "fy", name: "Western Frisian"),
        LanguageOption(code: "ga", name: "Irish"),
        LanguageOption(code: "gd", name: "Scottish Gaelic"),
        LanguageOption(code: "gl", name: "Galician"),
        LanguageOption(code: "gn", name: "Guarani"),
        LanguageOption(code: "gom", name: "Goan Konkani"),
        LanguageOption(code: "gu", name: "Gujarati"),
        LanguageOption(code: "ha", name: "Hausa"),
        LanguageOption(code: "haw", name: "Hawaiian"),
        LanguageOption(code: "he", name: "Hebrew"),
        LanguageOption(code: "hi", name: "Hindi"),
        LanguageOption(code: "hmn", name: "Hmong"),
        LanguageOption(code: "hr", name: "Croatian"),
        LanguageOption(code: "ht", name: "Haitian Creole"),
        LanguageOption(code: "hu", name: "Hungarian"),
        LanguageOption(code: "hy", name: "Armenian"),
        LanguageOption(code: "id", name: "Indonesian"),
        LanguageOption(code: "ig", name: "Igbo"),
        LanguageOption(code: "ilo", name: "Ilocano"),
        LanguageOption(code: "is", name: "Icelandic"),
        LanguageOption(code: "it", name: "Italian"),
        LanguageOption(code: "ja", name: "Japanese"),
        LanguageOption(code: "jv", name: "Javanese"),
        LanguageOption(code: "ka", name: "Georgian"),
        LanguageOption(code: "kk", name: "Kazakh"),
        LanguageOption(code: "km", name: "Khmer"),
        LanguageOption(code: "kn", name: "Kannada"),
        LanguageOption(code: "ko", name: "Korean"),
        LanguageOption(code: "kri", name: "Krio"),
        LanguageOption(code: "ku", name: "Northern Kurdish"),
        LanguageOption(code: "ky", name: "Kyrgyz"),
        LanguageOption(code: "la", name: "Latin"),
        LanguageOption(code: "lb", name: "Luxembourgish"),
        LanguageOption(code: "lg", name: "Luganda"),
        LanguageOption(code: "ln", name: "Lingala"),
        LanguageOption(code: "lo", name: "Lao"),
        LanguageOption(code: "lt", name: "Lithuanian"),
        LanguageOption(code: "lus", name: "Mizo"),
        LanguageOption(code: "lv", name: "Latvian"),
        LanguageOption(code: "mai", name: "Maithili"),
        LanguageOption(code: "mg", name: "Malagasy"),
        LanguageOption(code: "mi", name: "Maori"),
        LanguageOption(code: "mk", name: "Macedonian"),
        LanguageOption(code: "ml", name: "Malayalam"),
        LanguageOption(code: "mn", name: "Mongolian"),
        LanguageOption(code: "mni", name: "Manipuri"),
        LanguageOption(code: "mr", name: "Marathi"),
        LanguageOption(code: "ms", name: "Malay"),
        LanguageOption(code: "mt", name: "Maltese"),
        LanguageOption(code: "my", name: "Burmese"),
        LanguageOption(code: "nb", name: "Norwegian"),
        LanguageOption(code: "ne", name: "Nepali"),
        LanguageOption(code: "nl", name: "Dutch"),
        LanguageOption(code: "no", name: "Norwegian (Bokmal)"),
        LanguageOption(code: "nso", name: "Sepedi"),
        LanguageOption(code: "ny", name: "Chichewa"),
        LanguageOption(code: "om", name: "Oromo"),
        LanguageOption(code: "or", name: "Odia"),
        LanguageOption(code: "pa", name: "Punjabi"),
        LanguageOption(code: "pl", name: "Polish"),
        LanguageOption(code: "ps", name: "Pashto"),
        LanguageOption(code: "pt", name: "Portuguese"),
        LanguageOption(code: "qu", name: "Quechua"),
        LanguageOption(code: "ro", name: "Romanian"),
        LanguageOption(code: "ru", name: "Russian"),
        LanguageOption(code: "rw", name: "Kinyarwanda"),
        LanguageOption(code: "sa", name: "Sanskrit"),
        LanguageOption(code: "sd", name: "Sindhi"),
        LanguageOption(code: "si", name: "Sinhala"),
        LanguageOption(code: "sk", name: "Slovak"),
        LanguageOption(code: "sl", name: "Slovenian"),
        LanguageOption(code: "sm", name: "Samoan"),
        LanguageOption(code: "sn", name: "Shona"),
        LanguageOption(code: "so", name: "Somali"),
        LanguageOption(code: "sq", name: "Albanian"),
        LanguageOption(code: "sr", name: "Serbian"),
        LanguageOption(code: "su", name: "Sundanese"),
        LanguageOption(code: "sv", name: "Swedish"),
        LanguageOption(code: "sw", name: "Swahili"),
        LanguageOption(code: "ta", name: "Tamil"),
        LanguageOption(code: "te", name: "Telugu"),
        LanguageOption(code: "tg", name: "Tajik"),
        LanguageOption(code: "th", name: "Thai"),
        LanguageOption(code: "ti", name: "Tigrinya"),
        LanguageOption(code: "tk", name: "Turkmen"),
        LanguageOption(code: "tl", name: "Tagalog"),
        LanguageOption(code: "tr", name: "Turkish"),
        LanguageOption(code: "ts", name: "Tsonga"),
        LanguageOption(code: "tt", name: "Tatar"),
        LanguageOption(code: "ug", name: "Uyghur"),
        LanguageOption(code: "uk", name: "Ukrainian"),
        LanguageOption(code: "ur", name: "Urdu"),
        LanguageOption(code: "uz", name: "Uzbek"),
        LanguageOption(code: "vi", name: "Vietnamese"),
        LanguageOption(code: "xh", name: "Xhosa"),
        LanguageOption(code: "yi", name: "Yiddish"),
        LanguageOption(code: "yo", name: "Yoruba"),
        LanguageOption(code: "zh", name: "Chinese"),
        LanguageOption(code: "zh-cn", name: "Chinese (Simplified)"),
        LanguageOption(code: "zh-tw", name: "Chinese (Traditional)"),
        LanguageOption(code: "zu", name: "Zulu")
    ]

    static let defaultCode: String = "en"

    static func name(for code: String) -> String {
        all.first(where: { $0.code == code })?.name ?? code.uppercased()
    }
}

